# Generated by Django 3.1.7 on 2021-05-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSale', '0002_cart_item_itemcart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='digital',
        ),
    ]
