# Generated by Django 3.1.7 on 2021-05-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSale', '0006_auto_20210507_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcart',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appSale.item'),
        ),
    ]
