# Generated by Django 3.1.7 on 2021-06-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSale', '0008_auto_20210603_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestaff',
            name='saleCounter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
