# Generated by Django 3.1.7 on 2021-06-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSale', '0012_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='content',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
